version: "3"

services:
    app:
        container_name: "alice"
        build: .
        image: "alice-v2:latest"
        command: "npm run-script dev"
        volumes:
            - .:/home/node/
        environment:
            - NODE_ENV=${NODE_ENV:-development}
        links:
            - mongodb
    mongodb:
        image: mongo:latest
        container_name: "alice-mongo-container"
        volumes:
            - mongodata:/data/db
        ports:
            - "27017:27107"
volumes:
    mongodata: